tap "1password/tap"
tap "homebrew/cask-fonts"
tap "homebrew/cask"
tap "buildpacks/tap"

cask "alfred"
cask "amazon-workspaces"
cask "aws-vault"
cask "bettertouchtool"
cask "figma"
cask "github"
cask "hiddenbar"
cask "insomnia"
cask "iterm2"
cask "kube-forwarder"
cask "lens"
cask "miro"
cask "monitorcontrol"
cask "rectangle"
cask "slack"
cask "switchhosts"
cask "visual-studio-code"
cask "vmware-horizon-client"
cask "rancher"
# cask "warp"

cask "1password/tap/1password-cli"

cask "font-fira-code-nerd-font"
cask "font-hasklug-nerd-font"
cask "font-heavy-data-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-input"
cask "font-jetbrains-mono-nerd-font"
cask "font-monofur-nerd-font"
cask "font-monoid-nerd-font"

brew "mas"

brew "akamai"
brew "awscli"
brew "fzf"
brew "gh"
brew "git"
brew "go-jira"
brew "golang"
brew "groovy"
brew "helm"
brew "htop"
brew "jq"
brew "krew"
brew "kubecm"
brew "kubectl"
brew "kubectx"
brew "kubespy"
brew "kustomize"
brew "libsodium"
brew "nvm"
brew "pipenv"
brew "pyenv"
brew "rancher-cli"
brew "starship"
brew "yq"
brew "zsh-completion"
brew "zsh-syntax-highlighting"
brew "buildpacks/tap/pack"

# mas "XCode"

